apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  labels:
    {{- include "face-verification.labels" . | nindent 4 }}
data:
  kafka_host: {{ .Values.configmap.data.kafka_host }}
  kafka_port: {{ .Values.configmap.data.kafka_port }}
  kafka_consumer_topic: {{ .Values.configmap.data.kafka_consumer_topic }}
