apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "face-verification.fullname" . }}
  labels:
    {{- include "face-verification.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "face-verification.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "face-verification.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            # db secret
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db_secret.name }}
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db_secret.name }}
                  key: db_password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db_secret.name }}
                  key: db_name
            # db configmap
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.db_cofigmap.name }}
                  key: db_host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.db_cofigmap.name }}
                  key: db_port
            - name: DB_SCHEMA
              valueFrom:
                configMapKeyRef:
                    name: {{ .Values.db_cofigmap.name }}
                    key: db_schema
            # Kafka
            - name: KAFKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: kafka_host
            - name: KAFKA_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: kafka_port
            - name: KAFKA_CONSUMER_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: kafka_consumer_topic
          volumeMounts:
            - name: {{ .Values.faces_volume.name }}
              mountPath: {{ .Values.faces_volume.mountPath }}
      volumes:
        - name: {{ .Values.faces_volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.faces_pvc.name }}
