apiVersion: v1
kind: Pod
metadata:
  name: lebedev-face-verification-pod
spec:
  restartPolicy: Never
  containers:
    - name: lebedev-transaction-container
      image: kotbegemott/face-verification-service:1
      imagePullPolicy: Always
      ports:
        - containerPort: 8003
      resources:
        requests:
          memory: "200Mi"
          cpu: "200m"
        limits:
          memory: "400Mi"
          cpu: "400m"
      readinessProbe:
        httpGet:
          path: /ready
          port: 8003
        initialDelaySeconds: 60
        periodSeconds: 2
        successThreshold: 2
        failureThreshold: 5
      livenessProbe:
        httpGet:
          path: /live
          port: 8003
        initialDelaySeconds: 60
        periodSeconds: 2
        failureThreshold: 5
